#!/bin/sh

if ! test -d .git; then
    echo "Not in top-level of the repository."
    exit 1
fi

ln -sf ../../git-scripts/pre-commit.hook .git/hooks/pre-commit || exit 1
chmod +x .git/hooks/pre-commit

touch .git/hooks/applied || exit 1

echo "Git commit hooks are installed successfully."